
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'
use_frameworks!

pod 'Alamofire', '~> 4.0.1'
pod 'SwiftyJSON', '~> 3.1.1'
pod 'Unbox', '~> 2.1'

plugin 'cocoapods-keys', {
    :project => "CloudVisionKit",
    :target => "CloudVisionKit_Example",
    :keys => [
        "GoogleCloudVisionAPIKey"
    ]
}

target 'CloudVisionKit_Example' do
    pod "CloudVisionKit", :path => "../"
end

target 'CloudVisionKit_Tests' do
    pod "CloudVisionKit", :path => "../"
end
