
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'
use_frameworks!

pod 'Alamofire', '~> 3.5.0'
pod 'SwiftyJSON', '~> 2.4.0'
pod 'Unbox', '~> 1.9'

plugin 'cocoapods-keys', {
    :project => "CloudVisionKit",
    :target => "CloudVisionKit_Example",
    :keys => [
        "GoogleCloudVisionAPIKey"
    ]
}

target 'CloudVisionKit_Example' do
    pod "CloudVisionKit", :path => "../"
end

target 'CloudVisionKit_Tests' do
    pod "CloudVisionKit", :path => "../"
end
